/// Immutable domain model for a single bilirubin measurement from the device.
class Measurement {
  const Measurement({
    required this.measurementId,
    required this.babyId,
    required this.capturedAt,
    required this.receivedAt,
    required this.ageHours,
    required this.bilirubinMgDl,
    this.hasImage = false,
    this.encryptedImageRef,
    this.deviceId,
    this.modelVersion,
  });

  /// Globally unique ID generated by the device (UUID).
  final String measurementId;

  /// FK → babies.id
  final int babyId;

  /// When the device took the measurement (device clock; may drift).
  final DateTime capturedAt;

  /// When the app received the measurement from the device.
  final DateTime receivedAt;

  /// Baby's postnatal age at time of measurement (hours).
  final double ageHours;

  /// Measured serum bilirubin concentration (mg/dL).
  final double bilirubinMgDl;

  /// True if an encrypted image file exists for this measurement.
  final bool hasImage;

  /// Filename (not full path) of the AES-GCM encrypted image on disk.
  /// Null when [hasImage] is false.
  final String? encryptedImageRef;

  /// Device identifier that produced this measurement.
  final String? deviceId;

  /// On-device model version used for inference.
  final String? modelVersion;

  Measurement copyWith({
    String? measurementId,
    int? babyId,
    DateTime? capturedAt,
    DateTime? receivedAt,
    double? ageHours,
    double? bilirubinMgDl,
    bool? hasImage,
    String? encryptedImageRef,
    String? deviceId,
    String? modelVersion,
  }) {
    return Measurement(
      measurementId: measurementId ?? this.measurementId,
      babyId: babyId ?? this.babyId,
      capturedAt: capturedAt ?? this.capturedAt,
      receivedAt: receivedAt ?? this.receivedAt,
      ageHours: ageHours ?? this.ageHours,
      bilirubinMgDl: bilirubinMgDl ?? this.bilirubinMgDl,
      hasImage: hasImage ?? this.hasImage,
      encryptedImageRef: encryptedImageRef ?? this.encryptedImageRef,
      deviceId: deviceId ?? this.deviceId,
      modelVersion: modelVersion ?? this.modelVersion,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Measurement &&
          runtimeType == other.runtimeType &&
          measurementId == other.measurementId;

  @override
  int get hashCode => measurementId.hashCode;

  @override
  String toString() =>
      'Measurement(id: $measurementId, bilirubin: $bilirubinMgDl mg/dL, age: $ageHours h)';
}
