-- ================================================================
-- Bilirubin Companion App — complete Supabase schema
-- Replace the old migration entirely; run on a fresh project.
-- ================================================================

-- ── Core tables ──────────────────────────────────────────────────────────────

-- Every hospital that uses the system gets one row here.
-- The 'code' field is the short identifier staff type when initiating transfers.
create table public.hospitals (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  code       text not null unique,   -- e.g. 'RSU-01'
  created_at timestamptz not null default now()
);

-- One profile per auth.users entry.
-- hospital_id is NULL for parent accounts (they belong to no hospital).
create table public.user_profiles (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  hospital_id uuid references public.hospitals(id) on delete set null,
  role        text not null check (role in ('admin', 'staff', 'nurse', 'parent')),
  email       text not null,
  created_at  timestamptz not null default now()
);

-- Composite PK (hospital_id, local_id) matches the upsert conflict target
-- the Flutter app uses.  local_id is the SQLite rowid on the device.
create table public.babies (
  hospital_id   uuid        not null references public.hospitals(id) on delete cascade,
  local_id      integer     not null,
  name          text        not null,
  date_of_birth timestamptz not null,
  weight_kg     double precision not null,
  is_archived   boolean     not null default false,
  created_at    timestamptz not null,
  updated_at    timestamptz not null,
  primary key (hospital_id, local_id)
);

-- baby_local_id is nullable so the gun can push a measurement directly to
-- Supabase without knowing which baby is selected.  The app fills it in via
-- a subsequent upsert (ON CONFLICT DO UPDATE) when it processes the same
-- measurement through the normal flow.
--
-- Gun must use:  INSERT ... ON CONFLICT (measurement_id) DO NOTHING
-- App uses:      INSERT ... ON CONFLICT (measurement_id) DO UPDATE SET ...
-- This guarantees the app's fuller record (with baby_local_id) always wins.
create table public.measurements (
  measurement_id  text        primary key,   -- UUID generated by the gun
  hospital_id     uuid        not null references public.hospitals(id) on delete cascade,
  baby_local_id   integer,                   -- null = gun-direct push, filled in by app
  captured_at     timestamptz not null,
  received_at     timestamptz,               -- absent on gun-direct push
  age_hours       double precision,          -- absent on gun-direct push
  bilirubin_mg_dl double precision not null,
  has_image       boolean not null default false,
  device_id       text,
  model_version   text,
  created_at      timestamptz not null default now()
  -- No FK to babies: measurements outlive baby records and baby_local_id is
  -- nullable.  Integrity is enforced at the application level.
);

-- Pending transfers between hospitals.
-- from_hospital initiates; to_hospital accepts or rejects.
create table public.transfer_requests (
  id               uuid        primary key default gen_random_uuid(),
  baby_name        text        not null,
  from_hospital_id uuid        not null references public.hospitals(id),
  to_hospital_id   uuid        not null references public.hospitals(id),
  status           text        not null default 'pending'
                     check (status in ('pending','accepted','rejected','cancelled')),
  initiated_by     uuid        not null references auth.users(id),
  resolved_by      uuid        references auth.users(id),
  resolved_at      timestamptz,
  initiated_at     timestamptz not null default now()
);

-- Grants a parent account read-only visibility of one baby's data.
-- Cascades on baby deletion so stale access rows are cleaned up automatically.
create table public.parent_baby_access (
  parent_user_id uuid    not null references auth.users(id) on delete cascade,
  hospital_id    uuid    not null,
  baby_local_id  integer not null,
  granted_by     uuid    not null references auth.users(id),
  granted_at     timestamptz not null default now(),
  primary key (parent_user_id, hospital_id, baby_local_id),
  foreign key (hospital_id, baby_local_id)
    references public.babies(hospital_id, local_id) on delete cascade
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

create index on public.user_profiles     (hospital_id);
create index on public.measurements      (hospital_id, baby_local_id);
create index on public.measurements      (captured_at desc);
create index on public.measurements      (device_id);
create index on public.transfer_requests (from_hospital_id);
create index on public.transfer_requests (to_hospital_id);
create index on public.transfer_requests (status);
create index on public.parent_baby_access (hospital_id, baby_local_id);

-- ── Helper functions (used by RLS policies) ──────────────────────────────────

-- Returns the hospital_id of the currently authenticated user, or NULL.
create or replace function public.my_hospital_id()
returns uuid language sql stable security definer as $$
  select hospital_id
  from   public.user_profiles
  where  user_id = auth.uid()
$$;

-- Returns the role of the currently authenticated user, or NULL.
create or replace function public.my_role()
returns text language sql stable security definer as $$
  select role
  from   public.user_profiles
  where  user_id = auth.uid()
$$;

-- ── Row-Level Security ───────────────────────────────────────────────────────

alter table public.hospitals           enable row level security;
alter table public.user_profiles       enable row level security;
alter table public.babies              enable row level security;
alter table public.measurements        enable row level security;
alter table public.transfer_requests   enable row level security;
alter table public.parent_baby_access  enable row level security;

-- hospitals -------------------------------------------------------------------
-- Any logged-in user may read all hospitals.
-- (Needed for: showing own hospital name, and looking up transfer codes.)
-- Creating / editing hospitals is done via the Supabase dashboard or a
-- service-role migration script — no user-facing policy needed.
create policy "hospitals: authenticated read"
  on public.hospitals for select
  to authenticated
  using (true);

-- user_profiles ---------------------------------------------------------------
-- A user can always read their own profile.
create policy "user_profiles: read own"
  on public.user_profiles for select
  to authenticated
  using (user_id = auth.uid());

-- Admins can read every profile in their hospital (staff management screen).
create policy "user_profiles: admin reads same hospital"
  on public.user_profiles for select
  to authenticated
  using (
    hospital_id = public.my_hospital_id()
    and public.my_role() = 'admin'
  );

-- INSERT / UPDATE / DELETE are handled exclusively by Edge Functions that run
-- under the service-role key (create-staff, etc.).  No user-level policies.

-- babies ----------------------------------------------------------------------
create policy "babies: staff read"
  on public.babies for select
  to authenticated
  using (hospital_id = public.my_hospital_id());

create policy "babies: staff insert"
  on public.babies for insert
  to authenticated
  with check (hospital_id = public.my_hospital_id());

create policy "babies: staff update"
  on public.babies for update
  to authenticated
  using     (hospital_id = public.my_hospital_id())
  with check(hospital_id = public.my_hospital_id());

create policy "babies: staff delete"
  on public.babies for delete
  to authenticated
  using (hospital_id = public.my_hospital_id());

-- Parents can read the specific baby they are linked to.
create policy "babies: parent read linked"
  on public.babies for select
  to authenticated
  using (
    exists (
      select 1 from public.parent_baby_access pba
      where pba.parent_user_id = auth.uid()
        and pba.hospital_id    = babies.hospital_id
        and pba.baby_local_id  = babies.local_id
    )
  );

-- measurements ----------------------------------------------------------------
create policy "measurements: staff read"
  on public.measurements for select
  to authenticated
  using (hospital_id = public.my_hospital_id());

create policy "measurements: staff insert"
  on public.measurements for insert
  to authenticated
  with check (hospital_id = public.my_hospital_id());

-- Parents can read measurements for their linked baby.
create policy "measurements: parent read linked"
  on public.measurements for select
  to authenticated
  using (
    exists (
      select 1 from public.parent_baby_access pba
      where pba.parent_user_id = auth.uid()
        and pba.hospital_id    = measurements.hospital_id
        and pba.baby_local_id  = measurements.baby_local_id
    )
  );

-- transfer_requests -----------------------------------------------------------
create policy "transfers: admin read"
  on public.transfer_requests for select
  to authenticated
  using (
    public.my_role() = 'admin'
    and (from_hospital_id = public.my_hospital_id()
         or to_hospital_id  = public.my_hospital_id())
  );

create policy "transfers: admin insert"
  on public.transfer_requests for insert
  to authenticated
  with check (
    public.my_role() = 'admin'
    and from_hospital_id = public.my_hospital_id()
  );

create policy "transfers: admin update"
  on public.transfer_requests for update
  to authenticated
  using (
    public.my_role() = 'admin'
    and (from_hospital_id = public.my_hospital_id()
         or to_hospital_id  = public.my_hospital_id())
  );

-- parent_baby_access ----------------------------------------------------------
create policy "parent_access: read own"
  on public.parent_baby_access for select
  to authenticated
  using (parent_user_id = auth.uid());

create policy "parent_access: admin read"
  on public.parent_baby_access for select
  to authenticated
  using (
    hospital_id = public.my_hospital_id()
    and public.my_role() = 'admin'
  );

create policy "parent_access: admin insert"
  on public.parent_baby_access for insert
  to authenticated
  with check (
    hospital_id = public.my_hospital_id()
    and public.my_role() = 'admin'
  );

create policy "parent_access: admin delete"
  on public.parent_baby_access for delete
  to authenticated
  using (
    hospital_id = public.my_hospital_id()
    and public.my_role() = 'admin'
  );

-- ================================================================
-- HOW TO BOOTSTRAP THE FIRST ADMIN USER
-- ================================================================
-- 1. Create the hospital row:
--      insert into public.hospitals (name, code) values ('My Hospital', 'RSU-01');
--
-- 2. Have the admin sign up via the app (or create the user in the
--    Supabase Auth dashboard).
--
-- 3. Insert their profile manually (service role required):
--      insert into public.user_profiles (user_id, hospital_id, role, email)
--      values ('<auth-uuid>', '<hospital-uuid>', 'admin', 'admin@example.com');
--
-- After that, the admin can use the app's Staff Management screen to
-- add further staff members via the create-staff Edge Function.
-- ================================================================
