-- Mirror the current Drift schema as closely as possible in Supabase/Postgres.

create table if not exists public.babies (
  id bigint generated by default as identity primary key,
  name text not null,
  date_of_birth timestamptz not null,
  weight_kg double precision not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_archived boolean not null default false
);

create table if not exists public.devices (
  device_id text primary key,
  display_name text not null,
  transport text not null,
  is_paired boolean not null default false,
  paired_at timestamptz null,
  last_seen_at timestamptz null,
  firmware_version text null,
  public_key text null
);

create table if not exists public.measurements (
  measurement_id text primary key,
  baby_id bigint not null references public.babies(id),
  captured_at timestamptz not null,
  received_at timestamptz not null,
  age_hours double precision not null,
  bilirubin_mg_dl double precision not null,
  has_image boolean not null default false,
  encrypted_image_ref text null,
  device_id text null,
  model_version text null
);

create table if not exists public.audit_events (
  audit_event_id text primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  baby_id bigint null,
  measurement_id text null,
  device_id text null,
  details_json text null
);

create index if not exists idx_measurements_baby_id on public.measurements (baby_id);
create index if not exists idx_measurements_captured_at on public.measurements (captured_at desc);
create index if not exists idx_measurements_device_id on public.measurements (device_id);
create index if not exists idx_measurements_received_at on public.measurements (received_at desc);
create index if not exists idx_audit_events_created_at on public.audit_events (created_at desc);
create index if not exists idx_audit_events_baby_id on public.audit_events (baby_id);
create index if not exists idx_audit_events_measurement_id on public.audit_events (measurement_id);
create index if not exists idx_audit_events_device_id on public.audit_events (device_id);

comment on table public.babies is 'Matches the Drift Babies table in the Flutter app.';
comment on table public.devices is 'Matches the Drift Devices table in the Flutter app.';
comment on table public.measurements is 'Matches the Drift Measurements table in the Flutter app.';
comment on table public.audit_events is 'Matches the Drift AuditEvents table in the Flutter app.';