import 'package:drift/drift.dart';
import 'package:bilirubin/database/tables/babies_table.dart';

/// Drift table for bilirubin measurements received from the device.
///
/// The primary key is [measurementId], a UUID generated by the device,
/// enabling upsert-based deduplication (same ID → update, not duplicate insert).
class Measurements extends Table {
  /// UUID from the device — globally unique.
  TextColumn get measurementId => text()();

  /// FK → babies.id
  IntColumn get babyId => integer().references(Babies, #id)();

  /// Timestamp from the device clock (may drift).
  DateTimeColumn get capturedAt => dateTime()();

  /// Timestamp when the app received the data.
  DateTimeColumn get receivedAt => dateTime()();

  /// Baby's postnatal age in hours at time of measurement.
  RealColumn get ageHours => real()();

  /// Measured bilirubin concentration in mg/dL.
  RealColumn get bilirubinMgDl => real()();

  /// True if an encrypted image file exists for this measurement.
  BoolColumn get hasImage =>
      boolean().withDefault(const Constant(false))();

  /// Filename (basename only) of the AES-GCM encrypted image on disk.
  TextColumn get encryptedImageRef => text().nullable()();

  /// ID of the device that produced this measurement.
  TextColumn get deviceId => text().nullable()();

  /// On-device model version used for inference.
  TextColumn get modelVersion => text().nullable()();

  @override
  Set<Column> get primaryKey => {measurementId};
}
