import 'dart:typed_data';
import 'package:bilirubin/models/device_connection_state.dart';
import 'package:bilirubin/models/device_info.dart';

/// A measurement event emitted by the device.
class IncomingMeasurement {
  const IncomingMeasurement({
    required this.measurementId,
    required this.capturedAt,
    required this.bilirubinMgDl,
    required this.deviceId,
    required this.modelVersion,
    this.imageBytes,
  });

  /// UUID generated by the device – used for deduplication.
  final String measurementId;

  /// Device-clock timestamp (may drift; store alongside [receivedAt]).
  final DateTime capturedAt;

  /// Measured bilirubin concentration in mg/dL.
  final double bilirubinMgDl;

  /// Device identifier.
  final String deviceId;

  /// On-device model version used for inference.
  final String modelVersion;

  /// Raw JPEG image bytes from the device, or null if not available.
  final Uint8List? imageBytes;
}

/// Transport-agnostic interface for communicating with a bilirubin device.
///
/// Concrete implementations (Wi-Fi, BLE, fake) plug in via the provider layer.
abstract class DeviceRepository {
  /// Stream of connection lifecycle states.
  Stream<DeviceConnectionState> get connectionState;

  /// Stream of current device info (null when disconnected).
  Stream<DeviceInfo?> get deviceInfo;

  /// Stream of raw measurement events from the device.
  Stream<IncomingMeasurement> get measurements;

  /// Initiates a connection to the device.
  Future<void> connect();

  /// Gracefully disconnects from the device.
  Future<void> disconnect();

  /// Releases any underlying resources (timers, sockets, BLE handles).
  void dispose();
}
